shell:
  program: /Users/pw/.nix-profile/bin/fish
  args:
    - --login

window:
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10

  dynamic_title: true

startup_mode: SimpleFullscreen

# Base16 OceanicNext 256 - alacritty color config
# https://github.com/voronianski/oceanic-next-color-scheme
colors:
  # Default colors
  primary:
    background: '0x1b2b34'
    foreground: '0xc0c5ce'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1b2b34'
    cursor: '0xc0c5ce'

  # Normal colors
  normal:
    black:   '0x1b2b34'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xc0c5ce'

  # Bright colors
  bright:
    black:   '0x65737e'
    red:     '0xec5f67'
    green:   '0x99c794'
    yellow:  '0xfac863'
    blue:    '0x6699cc'
    magenta: '0xc594c5'
    cyan:    '0x5fb3b3'
    white:   '0xd8dee9'

  indexed_colors:
    - { index: 16, color: '0xf99157' }
    - { index: 17, color: '0xab7967' }
    - { index: 18, color: '0x343d46' }
    - { index: 19, color: '0x4f5b66' }
    - { index: 20, color: '0xa7adba' }
    - { index: 21, color: '0xcdd3de' }

scrolling:
  # Specifying '0' will disable scrolling.
  history: 100000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# copy to clipboard
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

key_bindings:
  - { key: K,      mods: Command,         chars: "\x0c"            }
  - { key: D,     mods: Command,       chars: "\x06\x76" } 
  - { key: D,     mods: Command|Shift, chars: "\x06\x73" }

# clickable urls
# is deprecated
# mouse:
# url:
# launcher:
# program: open
# modifiers: Command

live_config_reload: true
